variable "ENABLE_FEEDBACK_SUBMISSION" {}

variable "NAME" {}
variable "ENV" {}

variable "USE_ROUTE53" {}
variable "CUSTOM_DOMAIN_NAME" {}
variable "HOSTED_ZONE_ID" {}
variable "ACM_CERTIFICATE_ARN" {}

variable "COGNITO_ADMIN_GROUP_DESCRIPTION" {}
variable "MNO_COGNITO_USER_POOL_DOMAIN" {}
variable "THIRD_PARTY_COGNITO_USER_POOL_DOMAIN" {}
variable "COGNITO_REGISTERED_GROUP_DESCRIPTION" {}
variable "ACCOUNT_REGISTRATION_MODE" {}
variable "COGNITO_USER_POOL_DOMAIN" {}
variable "ALLOW_ADMIN_CREATE_USER_ONLY" {}
variable "ORIGIN_ID" {}

variable "DEVELOPMENT_MODE" {}
variable "NODE_ENV" {}

variable "DEPLOY_ROLE" {}
variable "APIGATEWAY_CUSTOM_DOMAIN_NAME" {}
variable "API_KEY_ROTATION_TRIGGER_FREQUENCY" {} 

variable "LOGGING_BUCKET" {}
