

variable "COGNITO_USER_POOL_CLIENT" {}
variable "AWS_ACCOUNT_ID" {}
variable "ALLOW_ADMIN_CREATE_USER_ONLY" {}
variable "COGNITO_REGISTERED_GROUP_ROLE_ARN" {}
# variable "BUCKET_REGIONAL_NAME"{}
# variable "LOCAL_DEVELOPMENT_MODE"{}
variable "COGNITO_ADMIN_GROUP_ROLE_ARN" {}
variable "COGNITO_REGISTERED_GROUP_DESCRIPTION" {}
variable "COGNITO_USER_POOL_DOMAIN" {}
variable "DNS_NAME" {}
variable "RESOURCE_PREFIX" {}
variable "AWS_REGION" {}
variable "CUSTOM_DOMAIN_NAME" {}
variable "COGNITO_USER_POOL" {}
variable "REGISTERED_GROUP_NAME" {}
variable "ADMIN_GROUP_NAME" {}
variable "COGNITO_ADMIN_GROUP_DESCRIPTION" {}
variable "COGNITO_SMS_CALLER_ROLE_ARN" {}
variable "MNO_COGNITO_USER_POOL_CLIENT" {}
variable "THIRD_PARTY_COGNITO_USER_POOL_CLIENT" {}
variable "THIRD_PARTY_COGNITO_USER_POOL_DOMAIN" {}
variable "MNO_COGNITO_USER_POOL_DOMAIN" {}
variable "THIRD_PARTY_COGNITO_USER_POOL" {}
variable "MNO_COGNITO_USER_POOL" {}
variable "MNO_ADMIN_GROUP_NAME" {}
variable "THIRD_PARTY_ADMIN_GROUP_NAME" {}